=== resonite-modding-group/resonite-mod-manifest/schemas/mod-schema.json
{
	"$id": "https://github.com/resonite-modding-group/resonite-mod-manifest/blob/master/schemas/mod-schema.json",
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"properties": {
		"name": {
			"type": "string",
			"description":"Name of the mod"
		},
		"id": {
			"type": "string",
			"description":"id of your mod, typically a reverse domain name followed by the name of the mod"
		},
		"description": {
			"type": "string",
			"description":"Brief description of your mod"
		},
		"category": {
			"type": "string",
			"description":"Category of your mod, if unsure, use Misc",
			"enum": [
				"Asset Importing",
				"Audio",
				"Bug Workaround",
				"Context Menu",
				"Controls",
				"Dashboard",
				"Hardware Integration",
				"Inspectors",
				"Libraries",
				"Memes",
				"Misc",
				"Optimization",
				"Plugins",
				"Protoflux",
				"Technical Tweaks",
				"Template",
				"Visual Tweaks",
				"Wizards"
			]
		},
		"sourceLocation": {
			"type": "string",
			"description":"Where the source of this mod can be found",
			"format": "uri"
		},
		"website": {
			"type": "string",
			"description":"Website or page for this specific mod if it is different than the sourceLocation",
			"format": "uri"
		},
		"tags": {
			"type": "array",
			"description":"Keywords to assist in searching for this mod",
			"items": {
				"type": "string"
			},
			"additionalItems": false
		},
		"flags": {
			"type": "array",
			"items": {
				"type": "string",
				"enum": ["broken", "deprecated", "file", "plugin"]
			},
			"additionalItems": false
		},
		"platforms": {
			"type": "array",
			"description":"Specifically supported platforms if a mod isn't expected to generally run on most platforms",
			"items": {
				"type": "string",
				"enum": ["android", "headless", "linux", "linux-native", "linux-wine", "windows", "other"]
			},
			"additionalItems": false
		},
		"additionalAuthors": {
			"type": "array",
			"description":"Additional authors or significant contributors aside from the main author",
			"items": {
				"type": "string"
			},
			"additionalItems": true
		},
		"versions": {
			"type": "object",
			"minProperties": 1,
			"propertyNames": {
				"pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
			},
			"additionalProperties": {
				"type": "object",
				"additionalProperties": false,
				"required": [
					"artifacts"
				],
				"properties": {
					"changelog": {
						"type": "string",
						"description":"Brief description of changes or fixes made"
					},
					"releaseUrl": {
						"type": "string",
						"description": "Link for this specific release",
						"format": "uri"
					},
					"conflicts": {
						"type": "object",
						"description": "Mod ids that are known to conflict with this mod",
						"additionalProperties": {
							"type": "object",
							"required": [
								"version"
							],
							"properties": {
								"version": {
									"type": "string",
									"description":"Versions that conflict, use * for all versions"
								}
							}
						}
					},
					"dependencies": {
						"type": "object",
						"description": "Other mods/libraries that this mod uses",
						"additionalProperties": {
							"type": "object",
							"required": [
								"version"
							],
							"properties": {
								"optional": {
									"type": "boolean",
									"default": false,
									"description": "Marks this dependency as optional. When set, the mod can function without it but may provide additional features or compatibility when available"
								},
								"version": {
									"type": "string",
									"description":"Minimum version required of this dependency"
								}
							}
						}
					},
					"artifacts": {
						"type": "array",
						"description":"All the files for this mod",
						"items": {
							"type": "object",
							"required": [
								"url",
								"sha256"
							],
							"properties": {
								"url": {
									"type": "string",
									"description":"Direct download url of the artifact",
									"format": "uri"
								},
								"filename": {
									"type": "string",
									"description":"Optional name override when saving the artifact",
									"pattern": "^\\S(?:.*\\S)?$"
								},
								"sha256": {
									"type": "string",
									"description":"Sha256 hash of the artifact",
									"pattern": "^[a-fA-F0-9]{64}$"
								},
								"installLocation": {
									"type": "string",
									"default": "/rml_mods",
									"description":"Target install path for the artifact. Defaults to `/rml_mods`. The root path `/` refers to the Resonite installation folder"
								}
							},
							"additionalProperties": false
						},
						"minItems": 1
					}
				}
			}
		}
	},
	"additionalProperties": false,
	"required": [
		"name",
		"id",
		"description",
		"category",
		"versions"
	]
}

=== resonite-modding-group/resonite-mod-manifest/manifest/com.tabbynet/ResonitePSVR2/info.json
{
	"name": "ResonitePSVR2",
	"id": "com.tabbynet.ResonitePSVR2",
	"description": "Enables support for special hardware features on the PlayStation VR2",
	"category": "Hardware Integration",
	"sourceLocation": "https://github.com/tabithamoon/ResonitePSVR2",
	"versions": {
		"1.2.2": {
			"releaseUrl": "https://github.com/tabithamoon/ResonitePSVR2/releases/tag/v1.2.2",
			"artifacts": [
				{
					"filename": "psvr2_toolkit_capi_loader.dll",
					"installLocation": "/rml_libs",
					"url": "https://github.com/tabithamoon/ResonitePSVR2/releases/download/v1.2.2/psvr2_toolkit_capi_loader.dll",
					"sha256": "e366143796fbb90edcb5cfb61afb05c7baa3e27ebaabe209bd7df16a3adced16"
				},
				{
					"filename": "libpsvr2_toolkit_capi_loader.so",
					"installLocation": "/rml_libs",
					"url": "https://github.com/tabithamoon/ResonitePSVR2/releases/download/v1.2.2/libpsvr2_toolkit_capi_loader.so",
					"sha256": "b4ae2029a1e86996a28b3eb78ee7a6d118b74a8da366338ab06dc0f6765d906f"
				},
				{
					"filename": "ResonitePSVR2.dll",
					"url": "https://github.com/tabithamoon/ResonitePSVR2/releases/download/v1.2.2/ResonitePSVR2.dll",
					"sha256": "41740304d8f21bcf8f983d89df332a6b8840f1f1c15e73744e80df9eb6c04065"
				}
			]
		},
		"1.2.1": {
			"releaseUrl": "https://github.com/tabithamoon/ResonitePSVR2/releases/tag/v1.2.1",
			"artifacts": [
				{
					"filename": "psvr2_toolkit_capi_loader.dll",
					"installLocation": "/rml_libs",
					"url": "https://github.com/tabithamoon/ResonitePSVR2/releases/download/v1.2.1/psvr2_toolkit_capi_loader.dll",
					"sha256": "e366143796fbb90edcb5cfb61afb05c7baa3e27ebaabe209bd7df16a3adced16"
				},
				{
					"filename": "libpsvr2_toolkit_capi_loader.so",
					"installLocation": "/rml_libs",
					"url": "https://github.com/tabithamoon/ResonitePSVR2/releases/download/v1.2.1/libpsvr2_toolkit_capi_loader.so",
					"sha256": "b4ae2029a1e86996a28b3eb78ee7a6d118b74a8da366338ab06dc0f6765d906f"
				},
				{
					"filename": "ResonitePSVR2.dll",
					"url": "https://github.com/tabithamoon/ResonitePSVR2/releases/download/v1.2.1/ResonitePSVR2.dll",
					"sha256": "1666606a5c28173de920ae12ade5209672781a01b1e3fbb31636e39e225dcd50"
				}
			]
		},
		"1.1.2": {
			"releaseUrl": "https://github.com/tabithamoon/ResonitePSVR2/releases/tag/v1.1.2",
			"artifacts": [{
				"url": "https://github.com/tabithamoon/ResonitePSVR2/releases/download/v1.1.2/ResonitePSVR2.dll",
				"sha256": "aae71b5a153f9103585d1e5adc5120dc8d70ffd3ba3da79d1705147489c06957"
			}]
		},
		"1.1.1": {
			"releaseUrl": "https://github.com/tabithamoon/ResonitePSVR2/releases/tag/v1.1.1",
			"artifacts": [{
				"url": "https://github.com/tabithamoon/ResonitePSVR2/releases/download/v1.1.1/ResonitePSVR2.dll",
				"sha256": "9881598f9ed913bbb9c45c1d148ecd4ee2168071a9db4c3d7c374ede538f4795"
			}]
		},
		"1.1.0": {
			"releaseUrl": "https://github.com/tabithamoon/ResonitePSVR2/releases/tag/v1.1.0",
			"artifacts": [{
				"url": "https://github.com/tabithamoon/ResonitePSVR2/releases/download/v1.1.0/ResonitePSVR2.dll",
				"sha256": "a783f2c74fb7a75ae28d87fb3833ba9509fa4c2a303af1f8940fa2d6fae4cd92"
			}]
		},
		"1.0.1": {
			"releaseUrl": "https://github.com/tabithamoon/ResonitePSVR2/releases/tag/v1.0.1",
			"artifacts": [{
				"url": "https://github.com/tabithamoon/ResonitePSVR2/releases/download/v1.0.1/ResonitePSVR2.dll",
				"sha256": "58510374a69c30902c0351b07fcbec3d1c4d889906fc5098628fa48499625c7b"
			}]
		}
	},
        "tags": [
            "psvr2",
            "eye",
            "tracking"
        ]
}

=== resonite-modding-group/resonite-mod-manifest/manifest/com.Sinduy/SlotInspectorHighlighter/info.json
{
	"name": "SlotInspectorHighlighter",
	"id": "com.Sinduy.SlotInspectorHighlighter",
	"description": "Adds a highlight to the hierarchy interface in the inspector to show which slot is currently being selected.",
	"category": "Inspectors",
	"sourceLocation": "https://github.com/sjsanjsrh/SlotInspectorHighlighter",
	"versions": {
		"1.0.6": {
			"releaseUrl": "https://github.com/sjsanjsrh/SlotInspectorHighlighter/releases/tag/1.0.6",
			"artifacts": [{
				"url": "https://github.com/sjsanjsrh/SlotInspectorHighlighter/releases/download/1.0.6/SlotInspectorHighlighter.dll",
				"filename": "SlotInspectorHighlighter.dll",
				"sha256": "13b11885bf65be1f6758f635c08ad645ae03e3fda13c109b93741d7c2bd29abd"
			}]
		},
		"1.0.3": {
			"releaseUrl": "https://github.com/sjsanjsrh/SlotInspectorHighlighter/releases/tag/v1.0.3",
			"artifacts": [{
				"url": "https://github.com/sjsanjsrh/SlotInspectorHighlighter/releases/download/v1.0.3/SlotInspectorHighlighter.dll",
				"sha256": "be997ad763dd2652d8f7f8dc7a609b80bc4b90dc81a98dd2c2fd8a486dae67ee"
			}]
		},
		"1.0.2": {
			"releaseUrl": "https://github.com/sjsanjsrh/SlotInspectorHighlighter/releases/tag/v1.0.2",
			"artifacts": [{
				"url": "https://github.com/sjsanjsrh/SlotInspectorHighlighter/releases/download/v1.0.2/SlotInspectorHighlighter.dll",
				"sha256": "cfe80b912f859e31b16c8273c6585098c91d75b4dc5ce74d20a372fe5cda7675"
			}]
		},
		"1.0.1": {
			"releaseUrl": "https://github.com/sjsanjsrh/SlotInspectorHighlighter/releases/tag/v1.0.1",
			"artifacts": [{
				"url": "https://github.com/sjsanjsrh/SlotInspectorHighlighter/releases/download/v1.0.1/SlotInspectorHighlighter.dll",
				"filename": "SlotInspectorHighlighter.dll",
				"sha256": "a0a2f0cf0586adf224a94b20f4f9f8afd317990521db632d04ced4a22cd2b8d3"
			}]
		},
		"1.0.0": {
			"releaseUrl": "https://github.com/sjsanjsrh/SlotInspectorHighlighter/releases/tag/v1.0.0",
			"artifacts": [{
				"url": "https://github.com/sjsanjsrh/SlotInspectorHighlighter/releases/download/v1.0.0/SlotInspectorHighlighter.dll",
				"filename": "SlotInspectorHighlighter.dll",
				"sha256": "5a263595f9412ffc7fab7c535590a1e9444197c41777f6f3ff463862596ce65c"
			}]
		}
	}
}

=== resonite-modding-group/resonite-mod-manifest/manifest/net.raidriar796/Lognt/info.json
{
	"name": "Lognt",
	"id": "net.raidriar796.lognt",
	"description": "Allows for disabling all logs, warnings, and errors from being written to disk.",
	"category": "Technical Tweaks",
	"sourceLocation": "https://github.com/Raidriar796/Lognt",
	"versions": {
		"1.1.1": {
			"releaseUrl": "https://github.com/Raidriar796/Lognt/releases/tag/1.1.1",
			"artifacts": [
				{
					"url": "https://github.com/Raidriar796/Lognt/releases/download/1.1.1/Lognt.dll",
					"filename": "Lognt.dll",
					"sha256": "1E0C52BBFB47C82EAB7625C6CE37F4899D5CA192429E1C4049120484FC66FDFA"
				}
			]
		},
		"1.1.0": {
			"releaseUrl": "https://github.com/Raidriar796/Lognt/releases/tag/1.1.0",
			"artifacts": [
				{
					"url": "https://github.com/Raidriar796/Lognt/releases/download/1.1.0/Lognt.dll",
					"filename": "Lognt.dll",
					"sha256": "0C2B00AAED7FA050040B62CB534AA9DA4DC26A862590507E5549D6FE85836FEE"
				}
			]
		},
		"1.0.0": {
			"releaseUrl": "https://github.com/Raidriar796/Lognt/releases/tag/1.0.0",
			"artifacts": [
				{
					"url": "https://github.com/Raidriar796/Lognt/releases/download/1.0.0/Lognt.dll",
					"filename": "Lognt.dll",
					"sha256": "1F69BE8F97EEBB89F7C86286E3540966D176F160AB3D91003C8DF9BB96C2F81A"
				}
			]
		}
	}
}

=== resonite-modding-group/resonite-mod-manifest/manifest/com.Sinduy/DoNotRunAwaySceneInspecter/info.json
{
	"name": "DoNotRunAwaySceneInspecter",
	"id": "com.Sinduy.DoNotRunAwaySceneInspecter",
	"description": "This mod prevents the scene inspector from moving away form user when they are trying to inspect a scene.",
	"category": "Inspectors",
	"sourceLocation": "https://github.com/sjsanjsrh/DoNotRunAwaySceneInspecter",
	"versions": {
		"1.0.5": {
			"releaseUrl": "https://github.com/sjsanjsrh/DoNotRunAwaySceneInspecter/releases/tag/1.0.5",
			"artifacts": [{
				"url": "https://github.com/sjsanjsrh/DoNotRunAwaySceneInspecter/releases/download/1.0.5/DoNotRunAwaySceneInspecter.dll",
				"filename": "DoNotRunAwaySceneInspecter.dll",
				"sha256": "ec022ba693587dfc67773e226295ab5d79418cb4384c3930492b72e2e89b4812"
			}]
		},
		"1.0.1": {
			"releaseUrl": "https://github.com/sjsanjsrh/DoNotRunAwaySceneInspecter/releases/tag/v1.0.1",
			"artifacts": [{
				"url": "https://github.com/sjsanjsrh/DoNotRunAwaySceneInspecter/releases/download/v1.0.1/DoNotRunAwaySceneInspecter.dll",
				"filename": "DoNotRunAwaySceneInspecter.dll",
				"sha256": "a6c9c20c62661331bbd994a1d9749bb2bd2225d4dc1568b49695da8aece9812a"
			}]
		},
		"1.0.0": {
			"releaseUrl": "https://github.com/sjsanjsrh/DoNotRunAwaySceneInspecter/releases/tag/v1.0.0",
			"artifacts": [{
				"url": "https://github.com/sjsanjsrh/DoNotRunAwaySceneInspecter/releases/download/v1.0.0/DoNotRunAwaySceneInspecter.dll",
				"filename": "DoNotRunAwaySceneInspecter.dll",
				"sha256": "a2ee76df5361933db30e812d3fad60998409eba2dc14dfbf5dfca0d52ac6e0cf"
			}]
		}
	}
}

=== resonite-modding-group/resonite-mod-manifest/manifest/me.art0007i/DisableLegacyInventory/info.json
{
    "flags": ["deprecated"],
    "name": "DisableLegacyInventory",
    "id": "me.art0007i.DisableLegacyInventory",
    "description": "Disables the legacy inventory gesture, but it has a config option that can enable it again",
    "category": "Controls",
    "sourceLocation": "https://github.com/art0007i/DisableLegacyInventory",
    "versions": {
        "2.0.0": {
            "releaseUrl": "https://github.com/art0007i/DisableLegacyInventory/releases/tag/2.0.0",
            "artifacts": [
                {
                    "url": "https://github.com/art0007i/DisableLegacyInventory/releases/download/2.0.0/DisableLegacyInventory.dll",
                    "filename": "DisableLegacyInventory.dll",
                    "sha256": "84a5d0a9d5f031225f8cff9d7e18a3b12b196afb05b6c2b9f1fc0e2ddba45a87"
                }
            ]
        }
    }
}

=== resonite-modding-group/resonite-mod-manifest/manifest/ErrorJan/FixGrabWorld/info.json
{
	"name": "FixGrabWorld",
	"id": "ErrorJan.FixGrabWorld",
	"description": "This mod fixes the weird jump when you try using the GrabWorldLocomotion.",
	"category": "Bug Workaround",
	"sourceLocation": "https://github.com/ErrorJan/ResoniteMod-FixGrabWorld",
	"versions": {
		"1.0.0": {
			"releaseUrl": "https://github.com/ErrorJan/ResoniteMod-FixGrabWorld/releases/tag/1.0.0",
			"artifacts": [
				{
					"url": "https://github.com/ErrorJan/ResoniteMod-FixGrabWorld/releases/download/1.0.0/FixGrabWorld.dll",
					"sha256": "ce2c7fd0a214ce856844f45dad6637d777ebb7525bda9822f9baf4fc47c5f809"
				}
			]
		}
	}
}

=== resonite-modding-group/resonite-mod-manifest/manifest/net.dextraspace/AnimatorTrackReference/info.json
{
	"name": "AnimatorTrackReference",
	"id": "net.dextraspace.AnimatorTrackReference",
	"description": "Adds a button to Animator components to show a reference of the clips animation tracks. MyInspectors dependency needed unless you are hosting the world you are working in.",
	"category": "Inspectors",
	"sourceLocation": "https://github.com/Cyberboss/AnimatorTrackReference",
	"tags": [
		"animx"
	],
	"versions": {
		"1.0.0": {
			"dependencies": {
				"me.art0007i.MyInspectors": {
					"version": "*",
					"optional": true
				}
			},
			"releaseUrl": "https://github.com/Cyberboss/AnimatorTrackReference/releases/tag/v1.0.0",
			"artifacts": [{
				"url": "https://github.com/Cyberboss/AnimatorTrackReference/releases/download/v1.0.0/AnimatorTrackReference.dll",
				"sha256": "387e803d0e0f1afc830c478a3ea0cda4b50f61c8b7e3073739d294456ff2f062"
			}]
		},
		"1.0.1": {
			"dependencies": {
				"me.art0007i.MyInspectors": {
					"version": "*",
					"optional": true
				}
			},
			"releaseUrl": "https://github.com/Cyberboss/AnimatorTrackReference/releases/tag/v1.0.1",
			"artifacts": [{
				"url": "https://github.com/Cyberboss/AnimatorTrackReference/releases/download/v1.0.1/AnimatorTrackReference.dll",
				"sha256": "fe7da5710433c32bdd965f22415d308a11bc1ad61f1244a417a90c36be4d661f"
			}]
		}
	}
}

=== resonite-modding-group/resonite-mod-manifest/manifest/owo.Nytra/ExpandedMemberEditors/info.json
{
	"name": "ExpandedMemberEditors",
	"id": "owo.Nytra.ExpandedMemberEditors",
	"description": "Adds basic inspector UI for SyncVar and SyncDictionary.",
	"category": "Inspectors",
	"sourceLocation": "https://github.com/Nytra/ResoniteExpandedMemberEditors",
	"versions": {
		"1.0.0": {
			"releaseUrl": "https://github.com/Nytra/ResoniteExpandedMemberEditors/releases/tag/v1.0.0",
			"artifacts": [{
				"url": "https://github.com/Nytra/ResoniteExpandedMemberEditors/releases/download/v1.0.0/ExpandedMemberEditors.dll",
				"sha256": "1ce42cc9159b4e90823fd3ea1c5bd7e87fc4ae2659ef3d4735e05cb1c06988f6"
			}]
		},
		"1.1.0": {
			"releaseUrl": "https://github.com/Nytra/ResoniteExpandedMemberEditors/releases/tag/v1.1.0",
			"artifacts": [{
				"url": "https://github.com/Nytra/ResoniteExpandedMemberEditors/releases/download/v1.1.0/ExpandedMemberEditors.dll",
				"sha256": "f0e4a430084fc846ba59ff168cbcce8098d94f777cf0ef5e279575e4d41cf22e"
			}]
		}
	}
}
