=== resonite-modding-group/resonite-mod-manifest/schemas/mod-schema.json
{
	"$id": "https://github.com/resonite-modding-group/resonite-mod-manifest/blob/master/schemas/mod-schema.json",
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"properties": {
		"name": {
			"type": "string",
			"description":"Name of the mod"
		},
		"id": {
			"type": "string",
			"description":"id of your mod, typically a reverse domain name followed by the name of the mod"
		},
		"description": {
			"type": "string",
			"description":"Brief description of your mod"
		},
		"category": {
			"type": "string",
			"description":"Category of your mod, if unsure, use Misc",
			"enum": [
				"Asset Importing",
				"Audio",
				"Bug Workaround",
				"Context Menu",
				"Controls",
				"Dashboard",
				"Hardware Integration",
				"Inspectors",
				"Libraries",
				"Memes",
				"Misc",
				"Optimization",
				"Plugins",
				"Protoflux",
				"Technical Tweaks",
				"Template",
				"Visual Tweaks",
				"Wizards"
			]
		},
		"sourceLocation": {
			"type": "string",
			"description":"Where the source of this mod can be found",
			"format": "uri"
		},
		"website": {
			"type": "string",
			"description":"Website or page for this specific mod if it is different than the sourceLocation",
			"format": "uri"
		},
		"tags": {
			"type": "array",
			"description":"Keywords to assist in searching for this mod",
			"items": {
				"type": "string"
			},
			"additionalItems": false
		},
		"flags": {
			"type": "array",
			"items": {
				"type": "string",
				"enum": ["broken", "deprecated", "file", "plugin"]
			},
			"additionalItems": false
		},
		"platforms": {
			"type": "array",
			"description":"Specifically supported platforms if a mod isn't expected to generally run on most platforms",
			"items": {
				"type": "string",
				"enum": ["android", "headless", "linux", "linux-native", "linux-wine", "windows", "other"]
			},
			"additionalItems": false
		},
		"additionalAuthors": {
			"type": "array",
			"description":"Additional authors or significant contributors aside from the main author",
			"items": {
				"type": "string"
			},
			"additionalItems": true
		},
		"versions": {
			"type": "object",
			"minProperties": 1,
			"propertyNames": {
				"pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
			},
			"additionalProperties": {
				"type": "object",
				"additionalProperties": false,
				"required": [
					"artifacts"
				],
				"properties": {
					"changelog": {
						"type": "string",
						"description":"Brief description of changes or fixes made"
					},
					"releaseUrl": {
						"type": "string",
						"description": "Link for this specific release",
						"format": "uri"
					},
					"conflicts": {
						"type": "object",
						"description": "Mod ids that are known to conflict with this mod",
						"additionalProperties": {
							"type": "object",
							"required": [
								"version"
							],
							"properties": {
								"version": {
									"type": "string",
									"description":"Versions that conflict, use * for all versions"
								}
							}
						}
					},
					"dependencies": {
						"type": "object",
						"description": "Other mods/libraries that this mod uses",
						"additionalProperties": {
							"type": "object",
							"required": [
								"version"
							],
							"properties": {
								"optional": {
									"type": "boolean",
									"default": false,
									"description": "Marks this dependency as optional. When set, the mod can function without it but may provide additional features or compatibility when available"
								},
								"version": {
									"type": "string",
									"description":"Minimum version required of this dependency"
								}
							}
						}
					},
					"artifacts": {
						"type": "array",
						"description":"All the files for this mod",
						"items": {
							"type": "object",
							"required": [
								"url",
								"sha256"
							],
							"properties": {
								"url": {
									"type": "string",
									"description":"Direct download url of the artifact",
									"format": "uri"
								},
								"filename": {
									"type": "string",
									"description":"Optional name override when saving the artifact",
									"pattern": "^\\S(?:.*\\S)?$"
								},
								"sha256": {
									"type": "string",
									"description":"Sha256 hash of the artifact",
									"pattern": "^[a-fA-F0-9]{64}$"
								},
								"installLocation": {
									"type": "string",
									"default": "/rml_mods",
									"description":"Target install path for the artifact. Defaults to `/rml_mods`. The root path `/` refers to the Resonite installation folder"
								}
							},
							"additionalProperties": false
						},
						"minItems": 1
					}
				}
			}
		}
	},
	"additionalProperties": false,
	"required": [
		"name",
		"id",
		"description",
		"category",
		"versions"
	]
}

=== resonite-modding-group/resonite-mod-manifest/manifest/me.art0007i/ShowDriveSource/info.json
{
    "name": "ShowDriveSource",
    "id": "me.art0007i.ShowDriveSource",
    "description": "Allows you to see what is driving a field by simply clicking on the name of the field",
    "category": "Inspectors",
    "sourceLocation": "https://github.com/art0007i/ShowDriveSource",
    "versions": {
        "2.0.1": {
            "releaseUrl": "https://github.com/art0007i/ShowDriveSource/releases/tag/2.0.1",
            "artifacts": [
                {
                    "url": "https://github.com/art0007i/ShowDriveSource/releases/download/2.0.1/ShowDriveSource.dll",
                    "filename": "ShowDriveSource.dll",
                    "sha256": "c47e5b88277cfa4c1d365d122cd2bf3adbffc05ddd97887e6842eb2f92540704"
                }
            ]
        }
    }
}

=== resonite-modding-group/resonite-mod-manifest/manifest/me.art0007i/PresenceToggle/info.json
{
    "flags": ["deprecated"],
    "name": "PresenceToggle",
    "id": "me.art0007i.PresenceToggle",
    "description": "Allows you to toggle steam and discord rich presence",
    "category": "Misc",
    "sourceLocation": "https://github.com/art0007i/PresenceToggle",
    "versions": {
        "2.0.1": {
            "releaseUrl": "https://github.com/art0007i/PresenceToggle/releases/tag/2.0.1",
            "artifacts": [
                {
                    "url": "https://github.com/art0007i/PresenceToggle/releases/download/2.0.1/PresenceToggle.dll",
                    "filename": "PresenceToggle.dll",
                    "sha256": "43f705e761a2c28e70cd443af0e1ad7dc46bde8b61eab3b39d55c9cea9e8f934"
                }
            ]
        }
    }
}

=== resonite-modding-group/resonite-mod-manifest/manifest/com.nekometer.esnya/ViveStreamingFaceTracking/info.json
{
	"name": "ViveStreamingFaceTrackingForResonite",
	"id": "com.nekometer.esnya.ViveStreamingFaceTracking",
	"description": "Adds facial tracking using Vive Hub for HMDs such as Vive Focus 3, Vive XR Elite, and Vive Focus Vision.",
	"category": "Hardware Integration",
	"sourceLocation": "https://github.com/esnya/ViveStreamingFaceTrackingForResonite",
	"additionalAuthors": [
		"howardhuanghtc",
		"JLhtc"
	],
	"tags": [
		"eyes",
		"lips",
		"eye tracking",
		"vive streaming"
	],
	"versions": {
		"0.1.2": {
			"releaseUrl": "https://github.com/esnya/ViveStreamingFaceTrackingForResonite/releases/tag/v0.1.2.0",
			"artifacts": [{
				"url": "https://github.com/esnya/ViveStreamingFaceTrackingForResonite/releases/download/v0.1.2.0/ViveStreamingFaceTracking.dll",
				"sha256": "a27e423b3f6fec38a8f89979108176641bef31dfedf39c0771ba1364dc6b0c89"
			}]
		},
		"0.1.1": {
			"releaseUrl": "https://github.com/esnya/ViveStreamingFaceTrackingForResonite/releases/tag/v0.1.1.0",
			"artifacts": [{
				"url": "https://github.com/esnya/ViveStreamingFaceTrackingForResonite/releases/download/v0.1.1.0/ViveStreamingFaceTracking.dll",
				"sha256": "45b222ea4f2cc66e1125b4a31d6f389bc51f9ce398062b07c30fdd4f351a49b1"
			}]
		}
	}
}

=== resonite-modding-group/resonite-mod-manifest/manifest/me.art0007i/OutOfSightOverride/info.json
{
    "name": "OutOfSightOverride",
    "id": "me.art0007i.OutOfSightOverride",
    "description": "Ignores the out of sight check on buttons",
    "category": "Misc",
    "sourceLocation": "https://github.com/art0007i/OutOfSightOverride",
    "versions": {
        "1.0.0": {
            "releaseUrl": "https://github.com/art0007i/OutOfSightOverride/releases/tag/1.0.0",
            "artifacts": [
                {
                    "url": "https://github.com/art0007i/OutOfSightOverride/releases/download/1.0.0/OutOfSightOverride.dll",
                    "filename": "OutOfSightOverride.dll",
                    "sha256": "c7fef55525aa9bbcb96c42aa4271707497fd3f0466cb17f1bc1c37e907544c75"
                }
            ]
        }
    }
}

=== resonite-modding-group/resonite-mod-manifest/manifest/fr.baplar/JustLetItGo/info.json
{
	"name": "JustLetItGo",
	"id": "fr.baplar.JustLetItGo",
	"description": "Improves the behavior of the local asset queue, in particular to work around the 'clogging' that can sometimes affect it. Experimental mod, may help but might also cause crashes, use at your own peril!",
	"category": "Bug Workaround",
	"sourceLocation": "https://forge.chapril.org/Baplar/Resonite.JustLetItGo",
	"tags": [
	  "experimental",
		"stuck",
		"clear",
		"gather",
		"job"
	],
	"versions": {
		"1.4.0": {
			"releaseUrl": "https://forge.chapril.org/Baplar/Resonite.JustLetItGo/releases/tag/1.4.0",
			"artifacts": [
				{
					"url": "https://forge.chapril.org/Baplar/Resonite.JustLetItGo/releases/download/1.4.0/JustLetItGo.dll",
					"sha256": "662e1e927da86853314ac9f888dad61d69f2e35f11bf2e4fa1d10103f7956a78"
				}
			]
		}
	}
}

=== resonite-modding-group/resonite-mod-manifest/manifest/dog.glacier/ContextMenuBackOption/info.json
{
	"name": "ContextMenuBackOption",
	"id": "dog.glacier.ContextMenuBackOption",
	"description": "Adds a Back option to every Context Menu submenu.",
	"category": "Context Menu",
	"sourceLocation": "https://github.com/noblereign/ResoniteContextMenuBackOption",
	"versions": {
		"4.0.1": {
			"releaseUrl": "https://github.com/noblereign/ResoniteContextMenuBackOption/releases/tag/v4.0.1",
			"artifacts": [{
				"url": "https://github.com/noblereign/ResoniteContextMenuBackOption/releases/download/v4.0.1/ContextMenuBackOption.dll",
				"sha256": "16ec7ae67017f9bb9d46c525195cf6e66eeef3e21e6ee570125b229b4e58f23a"
			}]
		},
		"4.0.0": {
			"releaseUrl": "https://github.com/noblereign/ResoniteContextMenuBackOption/releases/tag/v4.0.0",
			"artifacts": [{
				"url": "https://github.com/noblereign/ResoniteContextMenuBackOption/releases/download/v4.0.0/ContextMenuBackOption.dll",
				"sha256": "4399a5ac5d8bec18e7f434ac298dc6ec4fcde387dd83960943abd4529c365e97"
			}]
		},
		"3.0.0": {
			"releaseUrl": "https://github.com/noblereign/ResoniteContextMenuBackOption/releases/tag/v3.0.0",
			"artifacts": [{
				"url": "https://github.com/noblereign/ResoniteContextMenuBackOption/releases/download/v3.0.0/ContextMenuBackOption.dll",
				"sha256": "58f89b02e7256bb70cd9088c77d9a81497f774c7b62aadd6875e89682b9292c1"
			}]
		},
		"2.3.2": {
			"releaseUrl": "https://github.com/noblereign/ResoniteContextMenuBackOption/releases/tag/v2.3.2",
			"artifacts": [{
				"url": "https://github.com/noblereign/ResoniteContextMenuBackOption/releases/download/v2.3.2/ContextMenuBackOption.dll",
				"sha256": "7ec3573545d5c788d7780b9a4b9aabb2750c8c300e8d059e0c57b16d196b12b7"
			}]
		},
		"2.3.1": {
			"releaseUrl": "https://github.com/noblereign/ResoniteContextMenuBackOption/releases/tag/v2.3.1",
			"artifacts": [{
				"url": "https://github.com/noblereign/ResoniteContextMenuBackOption/releases/download/v2.3.1/ContextMenuBackOption.dll",
				"sha256": "03adece33f50bf5425498f3397d9c80c7c18ae254ce7b8c614291e030dfe59b2"
			}]
		},
		"2.3.0": {
			"releaseUrl": "https://github.com/noblereign/ResoniteContextMenuBackOption/releases/tag/v2.3.0",
			"artifacts": [{
				"url": "https://github.com/noblereign/ResoniteContextMenuBackOption/releases/download/v2.3.0/ContextMenuBackOption.dll",
				"sha256": "b8d2b4ec03eabbf720c59c0388b0df2e65666861f34a8bfc557aca6b3283d4a0"
			}]
		}
	}
}

=== resonite-modding-group/resonite-mod-manifest/manifest/cat.colin/ResdbTools/info.json
{
  "name": "Resdb Tools",
  "id": "cat.colin.ResdbTools",
  "description": "Extends the inventory browser with tools to get and modify Resonite database records.",
  "category": "Dashboard",
  "sourceLocation": "https://forge.colintimbarndt.de/Colin/resonite-resdb-tools-mod",
  "tags": ["inventory", "resdb", "database", "cloud"],
  "versions": {
    "1.0.1": {
      "releaseUrl": "https://forge.colintimbarndt.de/Colin/resonite-resdb-tools-mod/releases/tag/v1.0.1",
      "artifacts": [
        {
          "url": "hhttps://forge.colintimbarndt.de/Colin/resonite-resdb-tools-mod/releases/download/v1.0.1/ResdbTools.dll",
          "sha256": "67361a23583e499e5bc4236303c43df7e533a3fdce4bd958769caa0e677fa977"
        }
      ],
      "changelog": "Initial RML release."
    }
  }
}

=== resonite-modding-group/resonite-mod-manifest/manifest/net.NepuShiro/ResoTabbed/info.json
{
	"name": "ResoTabbed",
	"id": "net.NepuShiro.ResoTabbed",
	"description": "Adds a Dynamic Variable to show when you're tabbed in or not",
	"category": "Misc",
	"sourceLocation": "https://github.com/NepuShiro/ResoTabbed",
	"versions": {
		"1.0.0": {
			"releaseUrl": "https://github.com/NepuShiro/ResoTabbed/releases/tag/1.0.0",
			"artifacts": [{
				"url": "https://github.com/NepuShiro/ResoTabbed/releases/download/1.0.0/ResoTabbed.dll",
				"sha256": "da445cd6a06ef9e443cb8474bcc72a898d4984f39b421cf8161128f41b9ae9c5"
			}]
		}
	}
}
